### PR TITLE
fix example

### LINKED ISSUE #169: `tm_g_heat_bygrade` example failing
```
library(scda)

ADSL <- synthetic_cdisc_data("latest")$adsl %>% slice(1:30)
ADEX <- synthetic_cdisc_data("latest")$adex %>% filter(USUBJID %in% ADSL$USUBJID)
ADAE <- synthetic_cdisc_data("latest")$adae %>% filter(USUBJID %in% ADSL$USUBJID)

# from tm_g_heat_bygrade example
add_visit <- function(data_need_visit) {
  visit_dates <- ADEX %>%
    filter(PARAMCD == "DOSE") %>%
    distinct(USUBJID, AVISIT, ASTDTM) %>%
    group_by(USUBJID) %>%
    arrange(ASTDTM) %>%
    mutate(next_vis = lead(ASTDTM), is_last = ifelse(is.na(next_vis), TRUE, FALSE)) %>%
    rename(this_vis = ASTDTM)
  data_visit <- data_need_visit %>%
    select(USUBJID, ASTDTM) %>%
    left_join(visit_dates, by = "USUBJID") %>%
    filter(ASTDTM > this_vis & (ASTDTM < next_vis | is_last == TRUE)) %>%
    left_join(data_need_visit)
  return(data_visit)
}

ADAE <- add_visit(ADAE)
x <- cdisc_dataset("ADAE", ADAE)

x$check_keys()
```

image

### PR DESCRIPTION
**Pull request by nikolas-burkoff**
Closes #169 - test tm_g_heat_bygrade roxygen example

image

### CODE REVIEW

File: R/tm_g_heat_bygrade.R [hunk 1]
```diff
@@ -57,7 +57,8 @@
 #'     select(USUBJID, ASTDTM) %>%
 #'     left_join(visit_dates, by = "USUBJID") %>%
 #'     filter(ASTDTM > this_vis & (ASTDTM < next_vis | is_last == TRUE)) %>%
-#'     left_join(data_need_visit)
+#'     left_join(data_need_visit) %>%
+#'     distinct()
```
Comment (gogonzo) [inline R/tm_g_heat_bygrade.R:61]: I guess this is fine. Looks like some extra visits in data_need_visits got into the range of this_vis < ASTFTM < next_vis or is_last.

Looks like generated visits data in scda has some inconstistency.

**Review by gogonzo — APPROVED** [review]
👍
